### ISSUE TITLE
conflict with crystallogy.

### ISSUE THREAD

**Issue by meelock** [shadowfacts/InductionCharger#1]
This mod's tile entity "charger" conflicts with Crystallogy's tile entity "charger".

a simplified crash report here:

java.lang.IllegalArgumentException: Duplicate id: charger
at net.minecraft.tileentity.TileEntity.func_145826_a(TileEntity.java:36)
at net.minecraftforge.fml.common.registry.GameRegistry.registerTileEntity(GameRegistry.java:253)
at de.comeight.crystallogy.CommonProxy.registerTileEntitys(CommonProxy.java:172)
at de.comeight.crystallogy.CommonProxy.init(CommonProxy.java:488)
at de.comeight.crystallogy.ClientProxy.init(ClientProxy.java:52)
at de.comeight.crystallogy.CrystallogyBase.init(CrystallogyBase.java:38)

**Comment by shadowfacts** [comment]
cc047f66dd04efb9dd19f6278d81a14c9579f12a
